os: Visual Studio 2017

build:
  verbosity: detailed

environment:
  matrix:
  - Build: bearsplate
    Configuration: Debug

cache:
  - c:\projects\deps -> .appveyor.yml

platform:
- x64

install:
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip"
  - set DEPS_DIR=C:\projects\deps

  - if not exist %DEPS_DIR% (
      mkdir %DEPS_DIR% &&
      cd %DEPS_DIR% &&
      appveyor DownloadFile %NINJA_URL% -FileName ninja.zip &&
      7z x ninja.zip -o%DEPS_DIR%\ninja > nul )

  - set BOOST_ROOT=C:\Libraries\boost_1_69_0
  - set NINJA_BIN=%DEPS_DIR%\ninja
  - set PATH=%NINJA_BIN%;%PATH%

  - ninja --version
  - clang-cl -v

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule init
  - git submodule update

build_script:
  - mkdir build
  - cd build
  - cmake .. -GNinja -DCMAKE_BUILD_TYPE=%Configuration%
                     -DCMAKE_CXX_COMPILER=clang-cl
                     -DCMAKE_C_COMPILER=clang-cl
  - cmake --build .

test_script:
  - ps: |
      & ctest --output-on-failure -j nproc
